---
########
########
## CI ##
########
########
name: Security Scan

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
# Don't need to run on push to master/main
on:
  push:
    branches-ignore:
      - 'master'
      - 'main'

###############
# Set the Job #
###############
jobs:
  Scan:
    # Name the Job
    name: Security
    # Set the agent to run on
    runs-on: ubuntu-latest
    ##################
    # Load all steps #
    ##################
    steps:
      - name: Wait for app build success
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build-success
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: CI
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Perform Some Step
        if: steps.wait-for-build-success.outputs.conclusion == 'success'
        run: echo "We have success"

      - name: Error message on failure
        if: steps.wait-for-build-success.outputs.conclusion == 'failure'
        run: echo "ERROR! Build failure!
